import { DocumentTypeValue, ScannedKycData } from '@/lib/kyc-schema';

export const MOCK_PROFILES: Record<DocumentTypeValue, ScannedKycData> = {
  pan_card: {
    firstName: "Rajesh",
    middleName: "Kumar",
    lastName: "Shrestha",
    dob: "1990-11-12",
    gender: "male",
    nationality: "Nepali",
    documentType: "pan_card",
    address: {
      country: "Nepal",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "metropolitan",
      city: "Kathmandu",
      ward_no: "4",
    },
  },
  drivers_license: {
    firstName: "Sabina",
    middleName: "",
    lastName: "Gurung",
    dob: "1996-07-21",
    gender: "female",
    nationality: "Nepali",
    documentType: "drivers_license",
    address: {
      country: "Nepal",
      province: "Gandaki",
      district: "Kaski",
      municipality: "metropolitan",
      city: "Pokhara",
      ward_no: "12",
    },
  },
  birth_certificate: {
    firstName: "Bipin",
    middleName: "Raj",
    lastName: "Karki",
    dob: "2005-01-30",
    gender: "male",
    nationality: "Nepali",
    documentType: "birth_certificate",
    address: {
      country: "Nepal",
      province: "Koshi",
      district: "Morang",
      municipality: "sub-metropolitan",
      city: "Biratnagar",
      ward_no: "6",
    },
  },
  citizenship: {
    firstName: "Anustha",
    middleName: "Laxmi",
    lastName: "Maharjan",
    dob: "2003-03-05",
    gender: "female",
    nationality: "Nepali",
    documentType: "citizenship",
    address: {
      country: "Nepal",
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "metropolitan",
      city: "Lalitpur",
      ward_no: "9",
    },
  },
  passport: {
    firstName: "Dipesh",
    middleName: "",
    lastName: "Thapa",
    dob: "1988-09-14",
    gender: "male",
    nationality: "Nepali",
    documentType: "passport",
    address: {
      country: "Nepal",
      province: "Bagmati",
      district: "Bhaktapur",
      municipality: "municipality",
      city: "Bhaktapur",
      ward_no: "3",
    },
  },
  national_id: {
    firstName: "Sunita",
    middleName: "Kumari",
    lastName: "Tamang",
    dob: "1999-04-18",
    gender: "female",
    nationality: "Nepali",
    documentType: "national_id",
    address: {
      country: "Nepal",
      province: "Bagmati",
      district: "Chitwan",
      municipality: "rural-municipality",
      city: "Bharatpur",
      ward_no: "15",
    },
  },
};